#-------------------------------------------------------------------------------
#		Variant information
#-------------------------------------------------------------------------------

VARIANT_NAME = atmel_sam4s_xplained_pro
DEVICE_PART = __SAM4SD32C__
DEVICE_CORE = cortex-m4
DEVICE_FREQUENCY = 120000000ul

include ../Makefile.rules
