#-------------------------------------------------------------------------------
#		Variant information
#-------------------------------------------------------------------------------

VARIANT_NAME = poppy_core
DEVICE_PART = __SAMG55G19__
DEVICE_CORE = cortex-m4
DEVICE_FREQUENCY = 120000000ul

include ../Makefile.rules

