#-------------------------------------------------------------------------------
#		Variant information
#-------------------------------------------------------------------------------

VARIANT_NAME = arduino_due
DEVICE_PART = __SAM3X8E__
DEVICE_CORE = cortex-m3
DEVICE_FREQUENCY = 84000000ul

include ../Makefile.rules

